const SAVE="jewels-cafe-save";
const ART="https://jewels-cafe.netlify.app/";
const FACES=["cust1.png","cust2.png","cust3.png","cust4.png"];
const MEAN={Descriptive:"Summarize the data you already have.",Inferential:"Use a sample to talk about a population.",Population:"Every unit the question is about.",Sample:"The units you actually measured.",Parameter:"A number about the whole population.",Statistic:"A number calculated from the sample.",SRS:"Every sample of that size has the same chance.",Stratified:"Random sample from every group.",Cluster:"Take whole randomly chosen clusters.",Systematic:"Random start, then every kth name.",Convenience:"Whoever is easiest — often biased.",Voluntary:"People choose themselves — often biased.",Experiment:"Researcher assigns a treatment.",Observational:"Researcher only watches.",Qualitative:"Labels or categories.",Quantitative:"Counts or measurements.",Nominal:"Names with no order.",Ordinal:"Ranks without equal units.",Interval:"Equal steps, zero is not none.",Ratio:"Equal steps and a true zero.",Mean:"Add the values and divide by how many.",Median:"Middle value when ordered. Resistant.",Mode:"Value that occurs most often.",Range:"Maximum minus minimum.",IQR:"Q3 minus Q1. Resistant.","Bar chart":"Separate bars for categories.",Histogram:"Touching bars over number intervals.","Skewed right":"Long tail toward large values.","Pie chart":"Parts of one whole.",r:"Linear strength from -1 to 1.",Slope:"Change in predicted y when x goes up by 1.",Association:"Variables move together. Not cause.",Causation:"A change in x produces a change in y.",Complement:"P(not A)=1-P(A).",Independent:"One event does not change the other.",Disjoint:"Cannot happen on the same trial.",Binomial:"Successes in n independent yes/no trials.",Normal:"Mound curve named by mean and sd.",CLT:"For large n, the sample mean looks Normal.",Unbiased:"The estimator is centered at the parameter.",Wider:"Higher confidence makes a wider interval.",Narrower:"Bigger n makes a narrower interval.",H0:"Default claim. Usually no effect.",Ha:"The claim the study looks for.","P-value":"Chance of a result this extreme if H0 is true.","Reject H0":"P-value is smaller than alpha.","Type I":"Reject H0 when H0 is true.","Type II":"Fail to reject H0 when Ha is true.",Paired:"Two measures on the same subject.","Two-sample":"Two independent groups.",Counts:"Chi-square uses frequencies, not means.",F:"Between-group variation over within-group.",Ranks:"Replace raw numbers with ranks."};
function K(n,book,b,say,dishes,qs){return {n:n,book:book,b:b,say:say,dishes:dishes,orders:qs.map(function(x){return {p:x[0],w:x[1]}})}}
const CH=[
K("1A","Ch 1 Nature of Statistics","A sample is what you measured. A parameter describes everyone.","A sample is what you measured.","Descriptive,Inferential,Population,Sample,Parameter,Statistic".split(","),[["92 students averaged 6.4 hours. 6.4 is a","Statistic"],["True mean sleep of ALL students is a","Parameter"],["Those 92 students are the","Sample"],["Every student at the school is the","Population"],["These 92 averaged 6.4. No campus claim.","Descriptive"],["Michigan students sleep 6.4 hours, from 92 people.","Inferential"]]),
K("1B","Ch 1 Sampling","SRS gives every sample of that size the same chance.","SRS gives every sample of that size the same chance.","SRS,Stratified,Cluster,Systematic,Convenience,Voluntary,Experiment,Observational".split(","),[["Every group of 40 names is equally likely.","SRS"],["Split by year, pick 15 from EACH year.","Stratified"],["Pick 3 dorms and survey everyone inside.","Cluster"],["Random start, then every 10th name.","Systematic"],["Only the lunch table.","Convenience"],["Teacher assigns a review video at random.","Experiment"]]),
K("1C","Ch 1 Variable type","Qualitative = labels. Quantitative = amounts.","Ratio has a true zero.","Qualitative,Quantitative,Nominal,Ordinal,Interval,Ratio".split(","),[["Favorite topping is","Qualitative"],["Height in inches is","Quantitative"],["Jersey numbers as names only.","Nominal"],["Freshman / sophomore / junior.","Ordinal"],["Temperature in F.","Interval"],["Weight in pounds.","Ratio"]]),
K("2","Ch 2 Graphs","Bar/pie for categories. Histogram for numbers.","A histogram uses touching bars.","Bar chart,Pie chart,Histogram,Skewed right".split(","),[["Favorite color counts belong on a","Bar chart"],["Sleep hours in bins belong on a","Histogram"],["Long tail toward large values.","Skewed right"],["Parts of one whole.","Pie chart"]]),
K("3","Ch 3 Numbers that summarize","Mean is not resistant. Median is.","The median resists extreme tips.","Mean,Median,Mode,Range,IQR".split(","),[["Add and divide by n.","Mean"],["Middle of ordered data.","Median"],["Most common value.","Mode"],["Max minus min.","Range"],["Q3 minus Q1.","IQR"]]),
K("4","Ch 4 Scatterplots","r is between -1 and 1. Association is not causation.","A tight scatterplot is not proof of cause.","r,Slope,Association,Causation".split(","),[["Linear strength from -1 to 1.","r"],["Change in predicted y when x goes up by 1.","Slope"],["Variables move together.","Association"],["x produces a change in y.","Causation"]]),
K("5","Ch 5 Probability","P(not A)=1-P(A).","P(not A)=1-P(A).","Complement,Independent,Disjoint".split(","),[["P(not A)=1-P(A).","Complement"],["One event does not change the other.","Independent"],["Cannot happen on the same trial.","Disjoint"]]),
K("6","Ch 6 Random variables","Binomial: n yes/no trials. Normal: mound.","68 percent of a Normal sits within 1 sd.","Binomial,Normal".split(","),[["Successes in n independent yes/no trials.","Binomial"],["Mound curve named by mean and sd.","Normal"]]),
K("7","Ch 7 Sampling distributions","CLT: large n makes the sample mean look Normal.","The CLT is about the shape of the sample mean.","CLT,Unbiased".split(","),[["Large n makes the sample mean look mound-shaped.","CLT"],["Centered at the parameter means the estimator is","Unbiased"]]),
K("8","Ch 8 Confidence intervals","Higher confidence = wider. Bigger n = narrower.","95 percent is about the method.","Wider,Narrower".split(","),[["Higher confidence level makes the interval","Wider"],["Bigger n makes the interval","Narrower"]]),
K("9","Ch 9 Tests of significance","Reject H0 when P-value is smaller than alpha.","Failing to reject H0 is not proof H0 is true.","H0,Ha,P-value,Reject H0,Type I,Type II".split(","),[["Default no-effect claim.","H0"],["The claim the study looks for.","Ha"],["Chance of a result this extreme if H0 is true.","P-value"],["P-value smaller than alpha.","Reject H0"],["Reject H0 when H0 is true.","Type I"],["Miss Ha when Ha is true.","Type II"]]),
K("10","Ch 10 Comparing two groups","Two-sample = different people. Paired = same person.","Do not run a two-sample t on paired differences.","Two-sample,Paired".split(","),[["Two independent groups.","Two-sample"],["Before and after on the same student.","Paired"]]),
K("11","Ch 11 Chi-square","Chi-square uses counts, not means.","Do not put means into a chi-square table.","Counts".split(","),[["Chi-square needs frequencies, not means.","Counts"]]),
K("12","Ch 12 ANOVA","F is between-group variation over within-group.","ANOVA first, then follow-up.","F".split(","),[["Between-group variation over within-group.","F"]]),
K("13","Ch 13 Inference for regression","Do not trust a line outside the x range.","Check residuals before trusting the slope.","Slope".split(","),[["Predicted change in y per 1 x.","Slope"]]),
K("14","Ch 14 Nonparametrics","Ranks replace raw numbers when Normal is shaky.","If Normal is fine, the usual t is still OK.","Ranks".split(","),[["Replace the raw numbers with","Ranks"]])
];
const S={ci:0,coins:0,lives:3,served:0,goal:4,holding:null,run:false,paused:false,name:"",ready:false,done:{},order:null};
function $(id){return document.getElementById(id)}
function persist(){try{localStorage.setItem(SAVE,JSON.stringify({name:S.name,ci:S.ci,coins:S.coins,ready:S.ready,done:S.done}))}catch(e){}}
function restore(){try{var p=JSON.parse(localStorage.getItem(SAVE)||"null");if(!p)return;S.name=p.name||"";S.ci=Math.min(CH.length-1,Number(p.ci)||0);S.coins=p.coins||0;S.ready=!!p.ready;S.done=p.done||{};if(S.name && $("btnCont"))$("btnCont").hidden=false}catch(e){}}
function hideAll(){["boot","profile","teach","pick","settings","recipe"].forEach(function(id){var el=$(id);if(el)el.hidden=true});if($("paused"))$("paused").hidden=true}
function newGame(){hideAll();$("profile").hidden=false;try{$("pName").focus()}catch(e){}}
function clockIn(){S.name=(($("pName")&&$("pName").value)||"").trim()||"Chef";persist();openTeach()}
function contGame(){if(S.ready)startShift();else openTeach()}
function openTeach(){hideAll();$("teach").hidden=false;$("teachK").textContent=CH[S.ci].book;$("teachT").textContent=CH[S.ci].n;$("teachB").textContent=CH[S.ci].b}
function fillPick(){S.run=false;hideAll();$("pick").hidden=false;$("chList").innerHTML=CH.map(function(c,i){return "<button class='btn booth' type='button' onclick='pickCh("+i+")'>"+c.n+" · "+c.book+(S.done[c.n]?" *":"")+"</button>"}).join("")}
function pickCh(i){S.ci=i;S.ready=false;persist();openTeach()}
function goTitle(){S.run=false;hideAll();$("boot").hidden=false;if(S.name)$("btnCont").hidden=false}
function openMenu(){if($("settings"))$("settings").hidden=false}
function closeMenu(){if($("settings"))$("settings").hidden=true}
function togglePause(){if(S.paused)resumeRush();else{S.paused=true;if($("settings"))$("settings").hidden=true;if($("paused"))$("paused").hidden=false}}
function resumeRush(){S.paused=false;if($("paused"))$("paused").hidden=true;if($("settings"))$("settings").hidden=true;if(!S.run)startShift();else if($("coach"))$("coach").textContent="Rush on. Cook, then Serve."}
function spawn(){S.order=CH[S.ci].orders[S.served%CH[S.ci].orders.length]}
function startShift(){S.run=true;S.paused=false;S.ready=true;S.served=0;S.lives=3;S.holding=null;S.goal=4;persist();hideAll();spawn();draw();$("coach").textContent="Read the ticket. Cook the word. Then Serve."}
function draw(){var c=CH[S.ci];$("hCh").textContent=c.n;$("hMoney").textContent="$"+S.coins+"  "+S.served+"/"+S.goal;$("hLife").textContent="***".slice(0,Math.max(0,S.lives));var o=S.order;var face=ART+FACES[(S.served+S.ci)%4];$("slots").innerHTML=o?"<div><div class='ticket'>"+o.p+"</div><div class='who'><img src='"+face+"' alt='guest'></div></div>":"<div class='ticket'>Waiting</div>";$("heldName").textContent=S.holding||"nothing";$("menu").innerHTML=c.dishes.map(function(d){return "<button class='dish"+(S.holding===d?" on":"")+"' type='button' onclick='cook(\""+d+"\")'>"+d+"</button>"}).join("")}
function cook(d){if(S.paused)resumeRush();S.holding=d;$("coach").textContent=d+" — "+(MEAN[d]||"");draw()}
function serve(){if(S.paused)resumeRush();if(!S.run||!S.order){$("coach").textContent="Start a rush first.";return}if(!S.holding){$("coach").textContent="Cook a word first.";return}if(S.holding===S.order.w){S.coins+=8;S.served++;S.holding=null;if(S.served>=S.goal){S.run=false;S.done[CH[S.ci].n]=true;persist();hideAll();$("recipe").hidden=false;$("recLine").textContent=CH[S.ci].say;return}spawn();draw();$("coach").textContent="Yes. "+(MEAN[S.order.w]||"")}else{$("coach").textContent="Not "+S.holding+". Book answer: "+S.order.w+". "+(MEAN[S.order.w]||"");S.holding=null;draw()}}
function nextRush(){S.ci=Math.min(CH.length-1,S.ci+1);S.ready=false;persist();openTeach()}
restore();
